before:
  hooks:
    - go generate ./...
release:
  draft: true
builds:
  - main: .
    id: tom
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: ./go-tom-pdf/.
    id: tom-pdf
    binary: tom-pdf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

nfpms:
  - formats:
      - deb
    vendor: "https://github.com/jansorg/tom"
    homepage: "https://github.com/jansorg/tom"
    maintainer: "Joachim Ansorg <tom@ja-dev.eu>"
    description: "Tom is a command line tool to track time"
    license: ""
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    bindir: /usr/bin
    contents:
      - src: "scripts/completions/tom.sh"
        dst: "/etc/bash_completion.d/tom.sh"
    replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      amd64: amd64
      386: x86
    overrides:
      deb:
        dependencies:
          - bash-completion

archives:
  - replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      amd64: amd64
      386: x86
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^prep:'
      - '^wip'
