#!/usr/bin/env bash

lines=$(egrep -rhio 'i18n "[^"]+"' ./templates/ | sed -e 's/i18n "/p.Printf("/g' -e 's/"$/")/g')

cat - << EOF > go-tom/i18n_dummy.go
// This file is generated by update_template_i18n.bash
// It contains references to the translated strings used in our gohtml templates
package tom;
import (
    "golang.org/x/text/language"
    "golang.org/x/text/message"
)

func i18n_dummy(){
p:= message.NewPrinter(language.Tag{})
$lines
}
EOF