// This file is generated by update_template_i18n.bash
// It contains references to the translated strings used in our gohtml templates
package tom;
import (
    "golang.org/x/text/language"
    "golang.org/x/text/message"
)

func i18n_dummy(){
p:= message.NewPrinter(language.Tag{})
p.Printf("Date")
p.Printf("Start")
p.Printf("End")
p.Printf("Duration")
p.Printf("Notes")
p.Printf("Total")
p.Printf("Duration")
p.Printf("Exact duration")
p.Printf("Total")
p.Printf("Project")
p.Printf("Time range:")
p.Printf("Tracked time:")
p.Printf("Exact tracked time:")
p.Printf("Frames:")
}
